### ISSUE TITLE
Dependencies now retrieved on Windows

### ISSUE THREAD

**Issue by cino189** [edyu/wtf-zig-zon-2#1]
Hi, I am trying to run this sample project on windows but I get the following errors:
`zig build
duck.zig build-lib duck Debug native-native: error: error: unable to find Dynamic system library 'duckdb' using strategy 'paths_first'. searched paths:
  C:\Users\xxx\AppData\Local\zig\p\1220e182337ada061ebf86df2a73bda40e605561554f9dfebd6d1cd486a86c964e09\lib\duckdb.dll
  C:\Users\xxx\AppData\Local\zig\p\1220e182337ada061ebf86df2a73bda40e605561554f9dfebd6d1cd486a86c964e09\lib\duckdb.lib
  C:\Users\xxx\AppData\Local\zig\p\1220e182337ada061ebf86df2a73bda40e605561554f9dfebd6d1cd486a86c964e09\lib\libduckdb.a`
If I navigate that folder, I only see the libduckdb.so, which means it is correctly resolving some dependencies, although not all of them apparently. 

I also noticed there is an updated version of zig-duckdb (0.0.7) and if I update the zon file to point to that url I get the following error instead:
`thread 21020 panic: unable to find module 'libduckdb.lib'`

I noticed in the new version the module is not called anymore 'libduckdb.lib' but 'libduckdb.library', so I renamed it in the zig.build file and I got the same error as before: unable to find Dynamic system library 'duckdb' using strategy 'paths_first'.

Any idea why would this be the case?

**Comment by edyu** [comment]
Hi, .so is a shared library format for Linux only. It's not used for windows at all. You might need to instead create a package for windows using the released shared library `duckdb.dll` from duckdb. Unfortunately I don't do any zig work on Windows so I wouldn't know whether it does anything differently for .dll. I'm guessing that you can replace `zig-duckdb` with your own package that uses the windows [release](https://github.com/duckdb/duckdb/releases/download/v0.9.2/libduckdb-windows-amd64.zip).

**Comment by cino189** [comment]
You are right, indeed I had to use the windows version of the library. I then got stuck with some other windows issues with c libraries but that is not zig related. I ended up using a linux container on top of wsl at the end. 
Thank you for your answer.

**Comment by edyu** [comment]
My dev environment is also WSL2 on Windows (my friend said he took away my street-cred card because I use windows laptop ;) ). I found running Ubuntu on WSL works well enough. Good luck with your project. Sorry for the late reply because I was out of town for the last 3 weeks so didn't see the message until yesterday.
